### ISSUE TITLE
PRをマージしたら conflict が発生

### ISSUE THREAD

**Issue by kazupon** [gitlocalize/gitlocalize-issue#3]
## GitLocalize URL, if you have problem on GitLocalize
https://gitlocalize.com/repo/62/ja/en

## Background of the problem
下記URLのPRをマージする前は `ja/structure.md` はマージが発生していなかったのに、下記 PR をマージしたら、`ja/structure.md` の進捗ステータスが `conflict` と表示されるようになった。
https://github.com/open-source-translators/vue-ssr-docs/pull/26

以下は現時点発生しているスクリーンキャプチャ:
<img width="1186" alt="screen shot 2017-07-01 at 11 26 11 am" src="https://user-images.githubusercontent.com/72989/27758503-3894edd0-5e50-11e7-8281-3b7ac2132055.png">

## What is the problem
本家 `vuejs/vue-ssr-docs` から特に最新のコミットを同期していないにも関わらずに、conflict が発生するのが問題。

## How to solve the problem, if you have any idea.
進捗ステータス `conflict` ではなく、`100%`と表示されるべき。

**Comment by sotayamashita** [comment]
@kazupon コンフリクト解消いたしました。

**Comment by kazupon** [comment]
ありがとうございます！
確認したら、`103%` になっています！ 😭 

<img width="1170" alt="screen shot 2017-07-01 at 11 19 58 pm" src="https://user-images.githubusercontent.com/72989/27762803-db37928c-5eb3-11e7-9e84-8cac6e582768.png">

今のところ、こちらとしては問題ないので、お手すきのときにお願いします！
